services:
  flertur_db:
    container_name: flertur_db
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - default

  flertur_api:
    container_name: flertur_api
    build: ./api  
    ports:
      - "3005:3005" 
    networks:
      - default
    depends_on:
      flertur_db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@flertur_db:${POSTGRES_PORT}/${POSTGRES_DB}
    volumes:
      - ./api:/app
      - /app/node_modules

  flertur_frontend:
    container_name: flertur_frontend
    build: ./frontend
    user: "1000:1000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /var/www/flertur:/app/dist

volumes:
  postgres_data:

