services:
  flertur_db:
    container_name: flertur_db
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - default

  flertur_api:
    container_name: flertur_api
    build:
      context: ./app
      dockerfile: api/Dockerfile
    ports:
      - "3005:3005"
    networks:
      - default
    depends_on:
      flertur_db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@flertur_db:5432/${POSTGRES_DB}

  flertur_scraper:
    container_name: flertur_scraper
    build:
      context: ./app/scraper
      dockerfile: Dockerfile
    networks:
      - default
    depends_on:
      flertur_db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@flertur_db:5432/${POSTGRES_DB}?sslmode=disable
      MAX_DAY: "6"
      MAX_STATIONS: "8"
      NUM_THREADS: "2"
      REST_TIME: "30"

volumes:
  postgres_data:
